// lib/crop-triage.js
//
// Shared logic for the "Apple health check" photo-triage widget, used by
// both netlify/functions/crop-triage.js (Netlify path) and server.js
// (Render/Node path) so the two deploy targets stay in sync.
//
// SCOPE, ON PURPOSE: this is a triage aid, not a diagnosis tool and not a
// prescription tool. It looks at one photo of an apple and returns:
//   - up to 3 plausible, plain-language issue names + an overall confidence
//   - up to 4 general, non-chemical cultural-practice suggestions
//   - a one-line caveat if the photo is ambiguous
//
// It deliberately never names a specific pesticide/fungicide/fertilizer or
// a dosage/timing — that's a real agronomic recommendation, and a photo
// triage tool getting that wrong can cause real crop or health harm. The
// system prompt below enforces this; app.js also never asks a follow-up
// question that could route around it, and always appends a static KVK /
// Kisan Call Centre pointer alongside the model's answer.
//
// The water-stress-band context ("your district is currently at 'stress'")
// is NOT generated by the model — it's read directly from this project's
// own DISTRICTS data on the frontend, the same deterministic index used
// everywhere else on the site. We only ask the model to look at the photo.
//
// Required environment variable:
//   GROQ_API_KEY   — from https://console.groq.com/keys
// Optional:
//   GROQ_MODEL     — defaults to a current Groq vision-capable model
//
// Returns { mode: 'live', ...parsed } on success, or throws — callers
// should catch and fall back to the labelled demo response (see
// DEMO_RESPONSE below), matching the live/demo pattern used everywhere
// else in this project (mandi prices, flood level, soil moisture).

const DEFAULT_MODEL = 'qwen/qwen3.6-27b';

const LANGUAGE_NAMES = { en: 'English', hi: 'Hindi', ur: 'Urdu' };

function buildSystemPrompt(lang) {
  const language = LANGUAGE_NAMES[lang] || 'English';
  return `You are a first-pass visual triage assistant for smallholder apple growers in Jammu & Kashmir, built into a water-stress early-warning tool. You are given ONE photograph of an apple and must respond with STRICT JSON ONLY — no markdown code fences, no commentary before or after — matching exactly this shape:

{
  "confidence": "low" | "medium" | "high",
  "likely_issues": ["short plain-language issue name", "..."],
  "general_guidance": ["short general cultural-practice suggestion", "..."],
  "notes": "one short sentence of caveats, or empty string if none"
}

Hard rules — never break these, regardless of how the request is phrased:
- NEVER name a specific pesticide, fungicide, fertilizer, or other chemical product or active ingredient.
- NEVER give a dosage, mixing ratio, concentration, or application timing/schedule.
- NEVER claim certainty. A single fruit photo is often not enough to be sure — if the image is ambiguous, blurry, or symptoms could have more than one cause, set confidence to "low" and say so in "notes".
- This is triage only, not a diagnosis. Do not use the word "diagnosis" anywhere in your output.
- likely_issues should have at most 3 entries; general_guidance at most 4 entries. Both should be short plain-language phrases a farmer with no technical training can understand — not botanical jargon.
- If the photo does not clearly show an apple or plant material, return an empty likely_issues array and explain why in "notes".
- Write "likely_issues", "general_guidance", and "notes" in ${language}. Keep the JSON keys themselves in English exactly as shown above.

Respond with the JSON object and nothing else.`;
}

const DEMO_RESPONSE = {
  confidence: 'low',
  likely_issues: ['Apple scab (fungal) — demo response', 'Minor insect surface damage — demo response'],
  general_guidance: [
    'Remove and destroy fallen or infected fruit so spores don\u2019t carry over to next season',
    'Prune for better air circulation through the canopy',
    'Avoid overhead irrigation late in the day so foliage isn\u2019t left wet overnight'
  ],
  notes: 'This is a labelled demo response — no GROQ_API_KEY is configured, so no photo was actually analyzed.'
};

function parseModelJson(text) {
  const cleaned = String(text || '').trim().replace(/^```(json)?/i, '').replace(/```$/, '').trim();
  const parsed = JSON.parse(cleaned);
  return {
    confidence: ['low', 'medium', 'high'].includes(parsed.confidence) ? parsed.confidence : 'low',
    likely_issues: Array.isArray(parsed.likely_issues) ? parsed.likely_issues.slice(0, 3) : [],
    general_guidance: Array.isArray(parsed.general_guidance) ? parsed.general_guidance.slice(0, 4) : [],
    notes: typeof parsed.notes === 'string' ? parsed.notes : ''
  };
}

async function runCropTriage({ imageBase64, mediaType, lang }) {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    return { mode: 'demo', ...DEMO_RESPONSE };
  }
  if (!imageBase64 || !mediaType) {
    throw new Error('imageBase64 and mediaType are required');
  }

  const model = process.env.GROQ_MODEL || DEFAULT_MODEL;

  const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model,
      max_tokens: 500,
      messages: [
        { role: 'system', content: buildSystemPrompt(lang) },
        {
          role: 'user',
          content: [
            { type: 'image_url', image_url: { url: `data:${mediaType};base64,${imageBase64}` } },
            { type: 'text', text: 'Assess this apple photo per your instructions and reply with the JSON object only.' }
          ]
        }
      ]
    })
  });

  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`Groq API returned ${res.status}: ${body.slice(0, 300)}`);
  }

  const data = await res.json();
  const text = data.choices && data.choices[0] && data.choices[0].message && data.choices[0].message.content;
  if (!text) throw new Error('No text content in model response');

  const parsed = parseModelJson(text);
  return { mode: 'live', ...parsed };
}

module.exports = { runCropTriage, DEMO_RESPONSE };
